### ISSUE TITLE
Cant use getOrCreateBucket or deploySite functions inside nextjs route.ts file

### ISSUE THREAD

**Issue by FerhatAdibelli0** [remotion-dev/template-next-app-dir#5]
**Hi, I had to use some functions used in the deploy.mjs file in the nextjs route files. Because I want to first deploy the project every time I want a rendering. Normally when ı run node deploy.mjs, everything work as expected but when ı migrate some functions inside nextjs api route file I get an error like this:**

````
Compiling /api/lambda/render/route ...
 ⨯ ./node_modules/@remotion/compositor-darwin-arm64/compositor
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

````

**Comment by JonnyBurger** [comment]
It doesn't work indeed, see here for what to do: https://www.remotion.dev/docs/troubleshooting/bundling-bundle
