### ISSUE TITLE
In config.mjs RAM variable is set to 3009, is it intentional?

### ISSUE THREAD

**Issue by raymelon** [remotion-dev/template-next-app-dir#6]
I have encountered an error while running `npm run deploy`:

 `ValidationException: 'MemorySize' value failed to satisfy constraint: Member must have value less than or equal to 3008`

So I set the `RAM` to `3008` and I was able to deploy successfully, without issues.

But upon looking at `config.mjs`, 

I realized that `RAM` is set to `3009` instead of `3008`

```js
import { VERSION } from "remotion/version";

/**
 * Use autocomplete to get a list of available regions.
 * @type {import('@remotion/lambda').AwsRegion}
 */
export const REGION = "us-east-1";

export const SITE_NAME = "my-next-app";
export const RAM = 3009; // set as 3009
export const DISK = 2048;
export const TIMEOUT = 240;

```

I wonder if it is intentional to let the user know that his/her AWS account is limited in terms of quota.

If not, then we have to change the `RAM` from `3009` to `3008`

**Comment by JonnyBurger** [comment]
Thanks for reporting! You should have gotten the following error message as well, if not please let us know:

> 💡 This error indicates that you have a AWS account on the free tier or have been limited by your organization. Often times this can be solved by adding a credit card. See also: https://repost.aws/questions/QUKruWYNDYTSmP17jCnIz6IQ/questions/QUKruWYNDYTSmP17jCnIz6IQ/unable-to-set-lambda-memory-over-3008mb

Why do we set it to 3009?
It is a good value because you pay almost the same as 3008 but you get 3 CPUs instead of 2 :)

https://www.remotion.dev/docs/lambda/runtime#core-count--vcpus
